version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    build: ./db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_statement=all',
        '-c',
        'log_directory=/var/lib/postgresql/data/logs',
      ]
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - backend
  app:
    container_name: app
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}

    volumes:
      - ./src:/app/src
      - ./nestLogs:/app/nestLogs
    networks:
      - backend
volumes:
  pglogs:
    driver: local
  pgdata:
    driver: local
  nestLogs:
  app:
  node-modules:

networks:
  backend:
    driver: bridge
