version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    build: ./db
    restart: always
    command:
      ['postgres', '-c', 'log_statement=all']
    env_file:
      - .env

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/logs
  app:
    container_name: app
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend
    volumes:
      - .:/app
      - node-modules:/usr/app/node_modules
volumes:
  logs:
  pgdata:
  app:
  node-modules:

networks:
  backend:
    driver: bridge
