version: '3.0'

services:
  app:
    container_name: app
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/app

  db:
    container_name: postgresql
    image: postgres:15-alpine
    build: /db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend:
    driver: bridge